[package]
name = "sepha"
version = "0.1.0"
authors = ["chip reed <chip@chip.sh>"]
edition = "2018"
description = "A self contained 3rd party auth server for plug.dj"
license = "AGPL-3.0-or-later"

[dependencies]
